### ISSUE TITLE
More than one instance of bitcore-lib

### ISSUE THREAD

**Issue by nginnever** [Storj/storj.js#43]
When browserifying the latest commits I get this error initially destroying the storj module. 

```
Uncaught Error: More than one instance of bitcore-lib found. Please make sure to require bitcore-lib and check that submodules do not also include their own bitcore-lib dependency.
```
Bitcore lib has a version gaurd coded into that won't allow submodules to require it.

Storj core already requires bitcore-lib so when it is required for the Mnemonic in storj.js it is interfering. The simple fix is to generate a utility in core and require that through storj.js.

Or have storj-crypto module which started as a shim to allow webcrypto (which it cant do) contain all of the crypto modules so we don't run into this again.

**Comment by 161chihuahuas** [comment]
We are going to be removing bitcore altogether soon fwiw

**Comment by retrohacker** [comment]
@nginnever per @braydonf 's suggestion I matched the version of bitcore-mnemonic that was required by storj.js

having our `package.json` pin to `^1.0.0` and doing an `npm dedupe` in a `postinstall` should solve it as well, but is time consuming. We could also treat it as an implicit dependency, but I don't like that at all.

**Comment by retrohacker** [comment]
Closed by #44

**Comment by nginnever** [comment]
I am still seeing this error.

See https://github.com/Storj/storj.js/pull/44#issuecomment-287434878

I haven't tried npm dedupe either but that seems hacky

**Comment by braydonf** [comment]
You may need to clean out your node_modules @nginnever 

It has to do with how npm will resolve the semver compatibilities. There was a minor release of bitcore-mnemonic that bumped the "major" version of bitcore-lib, which caused the incompatibility and leading to two installs. Locking bitcore-mnemonic to the version before that release prevents that from happening.

BIP39 (mnemonic) is actually not complicated to implement. We may want to consider adding it directly to storj-lib storj-crypto (and use window.crypto.subtle) or using something like: https://github.com/bitcoinjs/bip39/blob/master/index.js

**Comment by retrohacker** [comment]
^^^

Have you run `rm -rf node_modules && npm install`?

**Comment by nginnever** [comment]
Thanks @braydonf

I did nuke my node_modules before testing this but still see the error. 

One thing I notice is that storj-core requires bitcore-lib v0.13.9 while bitcore-mnemonic jumped from v0.13.17 -> v0.14.0. Storj.js is trying to require bitcore-mnemonic v1.1.1 which require bitcore-lib v0.13.17

In any case I agree that adding this to our own crypto-lib would be better

**Comment by retrohacker** [comment]
@nginnever can you run:
`find ./node_modules -name 'bitcore-lib' -type d`

**Comment by retrohacker** [comment]
also, could you post your `package.json`?

**Comment by nginnever** [comment]
I was linking to a local storj-core module which must have caused it to get required twice. Removing the link fixes this.

**Comment by retrohacker** [comment]
@nginnever you can probably get away with linking, but remove the `node_modules` directory from the linked project.
